name: cross-icon
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - gensim
  - tqdm
  - matplotlib
  - adjusttext
  - pylint
  - pip
  - pip:
    - seaborn
    - ipdb
    - MulticoreTSNE
    - git+https://github.com/matplotlib/basemap.git
